name: example
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # calendar_flutter : ^1.0.5

  cupertino_icons: ^0.1.2

  event_calendar:
    path: ../

flutter:
  uses-material-design: true